### ISSUE TITLE
Add Transport Canada

### ISSUE THREAD

**Issue by thomasgohard** [jpmckinney/open_source_canada#13]
Transport Canada is now on GitHub: https://github.com/tc-ca.

**Comment by jpmckinney** [comment]
Thanks! Added: https://github.com/jpmckinney/open_source_canada/commit/e494032bcdaab27b4cffcabdcb8aa7cbbd8f6a51

**Comment by thomasgohard** [comment]
@jpmckinney looks like our repos aren’t getting listed on the Twitter account. We created a repo on Friday (https://github.com/tc-ca/uxsomcs-ecmux), but it didn’t appear in the Twitter feed.

**Comment by jpmckinney** [comment]
I've now added the IFTTT integration for the recently added organizations, so new repos from those orgs should be tweeted starting now. Thanks for reporting the issue!

**Comment by thomasgohard** [comment]
Thanks @jpmckinney.
